### PR TITLE
Update to Angular 16

### PR DESCRIPTION
**Pull request by jkubiszewski**

### CODE REVIEW

**Comment by AlexKhymenko** [comment]
@jkubiszewski Thank You so much!!!! I will merge this week.

**Comment by jkubiszewski** [comment]
When do you plan to publish it on npm?

**Comment by AlexKhymenko** [comment]
@jkubiszewski Only now seen your message. Published version 16.0.0

**Comment by jkubiszewski** [comment]
@AlexKhymenko Are you sure everything went well with the publication?
The package does not seem to contain my changes

**Comment by AlexKhymenko** [comment]
@jkubiszewski You are right. Publushed version 16.0.1 with Your changes

**Comment by jkubiszewski** [comment]
@AlexKhymenko Thank You!

**Comment by AlexKhymenko** [comment]
@jkubiszewski Thank to You for this pr !!!

**Pull request merged**
