### PR TITLE
Update to Angular 13 and RxJS 7

### PR DESCRIPTION
**Pull request by jkubiszewski**
Update to Angular 13 and RxJS 7

### CODE REVIEW

**Comment by AlexKhymenko** [comment]
@jkubiszewski Thank You very much!! You are awesome. I will merge it on Monday, right now away from computer

**Comment by jkubiszewski** [comment]
my pleasure ;)  when can we expect this version to be released?

**Comment by AlexKhymenko** [comment]
Today or tommorow will be release. Again Thank You!

**Comment by AlexKhymenko** [comment]
@jkubiszewski Done version 13 is available

**Pull request merged**
